{% set name = "cellpose" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cellpose-{{ version }}.tar.gz
  sha256: 4bc33826e4e611dcd3c513f97d081a883b2337b995a7929c0a9267597625535a

build:
  entry_points:
    - cellpose = cellpose.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
    - setuptools-scm
  run:
    - fastremap
    - natsort
    - numba
    - numpy >=1.20.0
    - opencv
    - python >=3.6
    - scipy
    - tifffile
    - pytorch >=1.6
    - tqdm

test:
  imports:
    - cellpose
    - cellpose.core
  commands:
    - pip list
    # - pip check
    - cellpose --help
  requires:
    - pip

about:
  home: https://github.com/MouseLand/cellpose
  summary: anatomical segmentation algorithm
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - gwaygenomics
